### ISSUE TITLE
implement checksum error detection.

### ISSUE THREAD

**Issue by Dennij** [Hermzy14/farmingSim#23]

**Comment by mustafyu** [comment]
A checksum is added in the RealCommunicationChannel class using CRC32. This method was chosen because it helps detect errors in the data in a quick and reliable way. When a command is sent, the checksum is calculated and added to the packet. When the response is received, the checksum is checked again to make sure the data hasn't been changed or corrupted. This method works well to catch mistakes that might happen while the data is being sent.

**Comment by Hermzy14** [comment]
Implemented checksum by creating a ChecksumHandler class. We use SHA-256 algorithm for calculating the checksum.
